version: "3"

services:

        nginx:
          restart: unless-stopped
          image: nginx
          container_name: nginx
          ports:
           - "80:80"
           - "443:443"
          volumes:
           - "/etc/nginx/conf.d"
           - "/etc/nginx/vhost.d"
           - "/usr/share/nginx/html"
           - "./volumes/proxy/certs:/etc/nginx/certs:ro"
       
        nginx-gen:
          restart: unless-stopped
          image: jwilder/docker-gen
          container_name: nginx-gen
          volumes:
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
            - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
          volumes_from:
            - nginx
          entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

        letsencrypt-nginx-proxy-companion:
          restart: unless-stopped
          image: jrcs/letsencrypt-nginx-proxy-companion
          container_name: letsencrypt-nginx-proxy-companion
          volumes_from:
            - nginx
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./volumes/proxy/certs:/etc/nginx/certs:rw"
          environment:
            - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

        myapp:
          restart: unless-stopped
          image: ecomod/effortsinvest:latest
          container_name: myappcontainer
          volumes:
            - "./rstudio_home:/home/cloud"
            #- "./dockercontext/EFForTS-ABM:/home/cloud/EFForTS-ABM"
            - "./dockercontext/netlogofolder:/home/cloud/netlogofolder"  
          expose:
            - "8787"
          environment:
            - VIRTUAL_HOST=c108-140.cloud.gwdg.de
            - VIRTUAL_NETWORK=nginx-proxy
            - VIRTUAL_PORT=80
            - USER=cloud
            - PASSWORD=UmT2kswp
            - LETSENCRYPT_HOST=c108-140.cloud.gwdg.de
            - LETSENCRYPT_EMAIL=shanss@gwdg.de
 
